stages:
  - stage: 'preparations'
    displayName: 'Preparations'
    jobs:
      - job: 'check-tools'
        displayName: 'Check Tools'
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              set -ex
              echo 'Hello world'