stages:
  - stage: 'preparations'
    displayName: 'Preparations'
    jobs:
      - job: 'check_tools'
        displayName: 'Check Tools'
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              set -e
              if [ -x "$(command -v az)" ]; then
                which az
                az version
              else
                echo 'az not found'
              fi
              if [ -x "$(command -v kubectl)" ]; then
                which kubectl
                kubectl version --client=true
              else
                echo 'kubectl not found'
              fi
              if [ -x "$(command -v helm)" ]; then
                which helm
                helm version
              else
                echo 'helm not found'
              fi
              if [ -x "$(command -v terraform)" ]; then
                which terraform
                terraform version
              else
                echo 'helm not found'
              fi
              if [ -x "$(command -v azcopy)" ]; then
                which azcopy
                if azcopy --version; then :; fi
              else
                echo 'azcopy not found'
              fi
              if [ -x "$(command -v aws)" ]; then
                which aws
                aws --version
              else
                echo 'aws not found'
              fi