stages:
  - stage: 'print_info'
    displayName: 'Print Information'
    jobs:
      - job: 'ubuntu_1804'
        displayName: 'ubuntu-18.04'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: none
          - task: Bash@3
            displayName: 'Print Information'
            inputs:
              failOnStderr: false
              noProfile: true
              noRc: true
              targetType: 'inline'
              script: |
                echo '========== User Information =========='
                id $(whoami)
                echo '========== Environment Variables =========='
                printenv
                echo '========== OS Information =========='
                cat /etc/os-release
                echo '========== Tool Version =========='
                command -v az
                az version
                command -v kubectl
                kubectl version --client=true
                command -v helm
                helm version
                command -v terraform
                terraform version
                command -v azcopy
                azcopy --version
                command -v aws
                aws --version
      - job: 'ubuntu_1604'
        displayName: 'ubuntu-16.04'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - checkout: none
          - task: Bash@3
            displayName: 'Print Information'
            inputs:
              failOnStderr: false
              noProfile: true
              noRc: true
              targetType: 'inline'
              script: |
                echo '========== User Information =========='
                id $(whoami)
                echo '========== Environment Variables =========='
                printenv
                echo '========== OS Information =========='
                cat /etc/os-release
                echo '========== Tool Version =========='
                command -v az
                az version
                command -v kubectl
                kubectl version --client=true
                command -v helm
                helm version
                command -v terraform
                terraform version
                command -v azcopy
                azcopy --version
                command -v aws
                aws --version
  - stage: 'install_tools'
    displayName: 'Install Tools'
    jobs:
      - job: 'install_tools'
        displayName: 'Install Tools'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: none
          - task: Bash@3
            displayName: 'Install Terraform'
            inputs:
              failOnStderr: true
              noProfile: true
              noRc: true
              targetType: 'inline'
              script: |
                curl -sL https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip -o terraform.zip
                unzip terraform.zip
                mv terraform $(Agent.ToolsDirectory)
          - task: Bash@3
            displayName: 'Install Helm'
            inputs:
              failOnStderr: true
              noProfile: true
              noRc: true
              targetType: 'inline'
              script: |
                curl -sL https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz -o helm.tgz
                tar -xvzf helm.tgz
                mv linux-amd64/helm $(Agent.ToolsDirectory)
          - task: Bash@3
            displayName: 'Print Tool Info'
            inputs:
              failOnStderr: false
              noProfile: true
              noRc: true
              targetType: 'inline'
              script: |
                PATH=$(Agent.ToolsDirectory):$PATH
                command -v terraform
                terraform version
                command -v helm
                helm version